baseURL = "https://montanamask.netlify.com"
languageCode = "en-us"
title = "Montana Mask"
theme = "ghostwriter"
Description = "Build details on Montana Mask a 3D printed respirator for experimental use in a time of PPE shortages for healthcare workers amid COVID19 pandemic."


[Params]
	# Blog description at the top of the homepage. Supports markdown.
	# description = "Trying to get you PPE however we can."
    intro = true
    
	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
    twitter = "https://twitter.com/VorosMD"
	slack = "https://join.slack.com/t/montanamaskmodifiers/shared_invite/zt-d4qpbwwk-ZFf0_d0rlbezTHCorIIXCA"
	sharegoogleplus = false
	shareLinkedIn = false

[[menu.main]]
	identifier = "home"
	name = "Home"
	url = "/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.


[[menu.main]]
	identifier = "montana"
	name = "Montana Mask"
	url = "/montana/"
	weight = 2 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "resus"
	name = "Resus Mask"
	url = "/resus/"
	weight = 3 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "filter"
	name = "Filter Material"
	url = "/filter/"
	weight = 4 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 11 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.
