baseURL = "/"
languageCode = "en-us"
title = "3d PPE"
theme = "ghostwriter"

[Params]
	# Blog description at the top of the homepage. Supports markdown.
	# description = "Trying to get you PPE however we can."
    intro = true
    headline = "My headline"
    description = "My description"

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
    twitter = "https://twitter.com/VorosMD"
    

# [[params.socialIcons]]
#   icon = "fa-twitter"
#   title = "Twitter"
#   url = "#"

[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 10 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "home"
	name = "Home"
	url = "/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.


[[menu.main]]
	identifier = "montana"
	name = "Montana Mask"
	url = "/montana/"
	weight = 2 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "resus"
	name = "Resus Mask"
	url = "/resus/"
	weight = 3 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "filter"
	name = "Filter Material"
	url = "/filter/"
	weight = 4 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.
